#' @title Pathway Enrichment Analysis using SPIA
#' @description This function performs patwhay analysis using SPIA method.
#' This function is used internally by runPathwayAnalysis.
#' @param summarizedExperiment The generated SummarizedExpriment object from DE analysis result.
#' @param network The network definition generated by getSPIAKEGGNetwork method.
#' @param pThreshold The p.value cutoff to select differentially expressed genes.
#' @param all The spia argument. See spia function.
#' @param ... A list of other passed arguments to spia. See spia function.
#' @return A dataframe of pathway analysis results
#' @details This function is used internally by runPathwayAnalysis.
#' @importFrom SummarizedExperiment SummarizedExperiment rowData
#' @importFrom dplyr %>%
.runSPIA <- function(summarizedExperiment, network, pThreshold, all, ...){

    DE_data <- rowData(summarizedExperiment)

    DE_filtered <- DE_data[DE_data$p.value <= pThreshold,]
    DE_stat <- DE_filtered %>% .$statistic %>% `names<-`(rownames(DE_filtered))

    if(is.null(all))
      all = rownames(DE_data)

    res <- .SPIAMod(de = DE_stat, all = all, path.info = network, ...)
    res <- res[, c('ID', 'pG')]
    colnames(res) <- c("pathway", "p.value")

    data.frame(
      ID = res$pathway,
      p.value = res$p.value,
      score = rep(0, nrow(res)),
      normalizedScore = rep(0, nrow(res)),
      stringsAsFactors = FALSE
    )
}

#' @title Pathway Enrichment Analysis using CePaORA
#' @description This function performs patwhay analysis using CePaORA method.
#' This function is used internally by runPathwayAnalysis.
#' @param summarizedExperiment The generated SummarizedExpriment object from DE analysis result.
#' @param network The pathways network catalouge generated by getCePaPathwayCatalogue.
#' @param cepaORA.args A list of other passed arguments to CePaORA. See CePa function.
#' @return A dataframe of pathway analysis results
#' @details This function is used internally by runPathwayAnalysis.
#' @importFrom SummarizedExperiment SummarizedExperiment rowData
#' @importFrom dplyr %>% select filter
#' @importFrom CePa cepa.all p.table
.runCePaORA <- function(summarizedExperiment, network, cepaORA.args = list()){

    DE_data <- rowData(summarizedExperiment)
    dif <- DE_data %>% filter(p.value <= cepaORA.args$pThreshold) %>% rownames(.)

    bk <- cepaORA.args$bk
    if(is.null(bk))
      bk <- rownames(DE_data)

    res <- cepa.all(dif = dif, bk = bk, pc = network, iter = cepaORA.args$iter, cen = cepaORA.args$cen, cen.name = cepaORA.args$cen.name)

    res.stats <- p.table(res) %>% apply(1, min) %>% data.frame(p.value = ., stringsAsFactors = FALSE)

    data.frame(
      pathway = rownames(res.stats),
      p.value = res.stats$p.value,
      score = rep(0, nrow(res.stats)),
      normalizedScore = rep(0, nrow(res.stats)),
      stringsAsFactors = FALSE
    )
}

#' @title Pathway Enrichment Analysis using CePaGSA
#' @description This function performs patwhay analysis using CePaGSA.
#' This function is used internally by runPathwayAnalysis.
#' @param summarizedExperiment The generated SummarizedExpriment object from DE analysis result.
#' @param network The pathways network catalouge generated by getCePaPathwayCatalogue.
#' @param cepaGSA.args A list of other passed arguments to CePaGSA. See CePa function.
#' @return A dataframe of pathway analysis results
#' @details This function is used internally by runPathwayAnalysis.
#' @importFrom SummarizedExperiment SummarizedExperiment rowData assay colData
#' @importFrom dplyr %>% select
#' @importFrom CePa sampleLabel cepa.all p.table
.runCePaGSA <- function(summarizedExperiment, network, cepaGSA.args){

    assay <- assay(summarizedExperiment)

    metadata <- colData(summarizedExperiment)
    contrast_mtx <- metadata$DEAnalysis$contrast
    design_mtx <- metadata$DEAnalysis$design

    firstCondition <- rownames(contrast_mtx)[which(contrast_mtx == 1)]
    secondCondition <- rownames(contrast_mtx)[which(contrast_mtx == -1)]

    firstSamples <- design_mtx[, firstCondition] %>% subset(. == 1) %>% names(.)
    secondSamples <- design_mtx[, secondCondition] %>% subset(. == 1) %>% names(.)

    group <- c(rep(1, length(firstSamples)), rep(0, length(secondSamples)))
    names(group) <- c(firstSamples, secondSamples)

    label <- sampleLabel(group, treatment = "1", control = "0")

    res <- cepa.all(mat = assay, label = label, pc = network, cen = cepaGSA.args$cen, cen.name = cepaGSA.args$cen.name, nlevel = cepaGSA.args$nlevel,
                          plevel = cepaGSA.args$plevel, iter = cepaGSA.args$iter)

    res.stats <- p.table(res) %>% apply(1, min) %>% data.frame(p.value = ., stringsAsFactors = FALSE)

    data.frame(
      pathway = rownames(res.stats),
      p.value = res.stats$p.value,
      score = rep(0, nrow(res.stats)),
      normalizedScore = rep(0, nrow(res.stats)),
      stringsAsFactors = FALSE
    )
}

#' @title Pathway Enrichment Analysis
#' @description This function performs patwhay analysis using SPIA, CePaORA, and CePaGSA methods.
#' @param summarizedExperiment The generated SummarizedExpriment object from DE analysis result.
#' @param network The pathways network object.
#' @param method The pathway analsyis method, including SPIA, cepaORA, and cepaGSA.
#' @param SPIAArgs A list of other passed arguments to fgsea. See spia function.
#' @param CePaORAArgs A list of other passed arguments to CePaORA. See CePa function.
#' @param CePaGSAArgs A list of other passed arguments to CePaGSA. See CePa function.
#' @return A dataframe of pathway analysis result
#' @importFrom SummarizedExperiment SummarizedExperiment assay
#' @importFrom dplyr %>%
#' @export
runPathwayAnalysis <- function(summarizedExperiment, network, method = c("SPIA", "cepaORA", "cepaGSA"),
                               SPIAArgs = list(all = NULL, nB = 2000, verbose = TRUE, beta = NULL, combine = "fisher", pThreshold = 0.05),
                              CePaORAArgs = list(bk = NULL, cen = default.centralities, cen.name = sapply(cen, function(x) ifelse(mode(x) == "name", deparse(x), x)), iter = 1000, pThreshold = 0.05),
                              CePaGSAArgs = list(mat = NULL, label = NULL, pc, cen = default.centralities, cen.name = sapply(cen, function(x) ifelse(mode(x) == "name", deparse(x), x)), nlevel = "tvalue_abs", plevel = "mean", iter = 1000)
){
    method <- match.arg(method)

    assay <- assay(summarizedExperiment)
    if(is.null(assay) | dim(assay)[1] == 0 | dim(assay)[2] == 0){
        stop("No expression data is in input data.")
    }

    if(is.null(network)){
        stop("The network needs to be prepared before running pathway enrichment analysis.")
    }

    paArgs <- NULL

    if(method == "SPIA"){

        if(any(sapply(network, function(x) length(x)) != 28)){
            stop("The network definition for SPIA should be matched with the returned network object from getSPIAKEGGNetwork().")
        }

        SPIAArgs.default <- list(all = NULL, nB = 2000, verbose = TRUE, beta = NULL, combine = "fisher", pThreshold = 0.05)

        if (any(!names(SPIAArgs) %in% names(SPIAArgs.default))) {
            stop("The names of arguments should be matched with SPIA definition.")
        }

        tmp <- SPIAArgs
        SPIAArgs <- SPIAArgs.default
        SPIAArgs[names(tmp)] <- SPIAArgs.default[names(tmp)]

        if(!SPIAArgs$combine %in% c("fisher", "norminv")){
            stop("The combine argument should be either 'fisher' or 'norminv'.")
        }

        if(SPIAArgs$pThreshold < 0 | SPIAArgs$pThreshold > 1){
            stop("The pThreshold must be between zero and one.")
        }

        paArgs <- SPIAArgs
    }

    if(method == "cepaORA"){



        CePaORAArgs.default = list(bk = NULL, cen = default.centralities, cen.name = sapply(cen, function(x) ifelse(mode(x) == "name", deparse(x), x)), iter = 1000, pThreshold = 0.05)

        if (any(!names(CePaORAArgs) %in% names(CePaORAArgs.default))) {
            stop("The names of arguments should be matched with SPIA definition.")
        }

        tmp <- CePaORAArgs
        CePaORAArgs <- CePaORAArgs.default
        CePaORAArgs[names(tmp)] <- CePaORAArgs.default[names(tmp)]

        if(CePaORAArgs$pThreshold < 0 | CePaORAArgs$pThreshold > 1){
            stop("The pThreshold must be between zero and one.")
        }

        paArgs <- CePaORAArgs
    }

    if(method == "cepaGSA"){

        CePaGSAArgs.default = list(mat = NULL, label = NULL, cen = default.centralities, cen.name = sapply(cen, function(x) ifelse(mode(x) == "name", deparse(x), x)), nlevel = "tvalue_abs", plevel = "mean", iter = 1000)

        if (any(!names(CePaGSAArgs) %in% names(CePaGSAArgs.default))) {
            stop("The names of arguments should be matched with SPIA definition.")
        }

        tmp <- CePaGSAArgs
        CePaGSAArgs <- CePaGSAArgs.default
        CePaGSAArgs[names(tmp)] <- CePaGSAArgs.default[names(tmp)]

        if(CePaGSAArgs$pThreshold < 0 | CePaGSAArgs$pThreshold > 1){
            stop("The pThreshold must be between zero and one.")
        }

        paArgs <- CePaGSAArgs
    }

    paArgs$summarizedExperiment <- summarizedExperiment
    paArgs$network <- network

    methodFnc <- switch(method,
                     SPIA = .runSPIA,
                     cepaORA = .runCePaORA,
                     cepaGSA = .runCePaGSA
                     )


    result <- do.call(methodFnc, paArgs)

    if (is.null(result)) {
        stop("There is an error in geneset analysis procedure.")
    }

    result$sample.size = ncol(assay(summarizedExperiment))
    result$name = result$ID

    return(result)
}